name: Captura Correio Diário

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Instalar Playwright
      run: |
        pip install playwright
        playwright install chromium

    - name: Instalar dependências
      run: pip install -r requirements.txt

    - name: Criar arquivo de credenciais
      shell: bash
      run: |
        cat << 'EOF' > service-account.json
        ${{ secrets.SERVICE_ACCOUNT_JSON }}
        EOF

    - name: Executar captura
      run: python main.py
